spring.datasource.url=jdbc:sqlite:./${gtd.persistence.bootstrap.clone-directory}/db/gtd-on-rails.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
gtd.persistence.bootstrap.repository-url=https://github.com/Victor-Saraiva-P/gtd-persistence-test.git
gtd.persistence.bootstrap.clone-directory=gtd-persistence-test
gtd.persistence.bootstrap.branch=main
