spring.datasource.url=jdbc:sqlite:./build/context-test.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.web.resources.add-mappings=false
api.project-name=https://gtdonrails.local
api.base-url=/errors
gtd.persistence.bootstrap.enabled=false
gtd.persistence.bootstrap.repository-url=https://github.com/Victor-Saraiva-P/gtd-persistence-test.git
gtd.persistence.bootstrap.clone-directory=gtd-persistence-test
gtd.persistence.bootstrap.branch=main
